language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 test
after_success:
- lein2 pallet-release push
env:
  global:
    secure: NVdXYm9En/plX8zwDR+5IAOL+aN64zmapXSnlC3uXJ7yMvUghRg7seJ7a+5VzA462BG1IGX4qnQwZwi+3tZUtYuwo7J+9EhVsAQHQQdAt8hourUEGVIMYxiafOi9JX+c08EarhFCbV7ojZFiuTcesKsoEDfEXAqFXJAKRn/pdFE=
